### ISSUE TITLE
Large amount of loglines "Ignoring Class '\x01', type 'A'"

### ISSUE THREAD

**Issue by jhogendorn** [scottt732/coredns-traefik#2]
As it says on the tin, the plugin is producing a large amount of log lines as such:

log:
```
coredns  | [INFO] plugin/traefik: Ignoring class '\x01', type 'A'
```

config:
```
traefik https://traefik.local/api {
        a 192.168.0.2
        refreshinterval 30
        ttl 5
        resolveapihost
        insecureskipverify
    }
```

**Comment by scottt732** [comment]
Sorry about that. I was just curious what else was coming across on my setup at home. I removed the log line.

**Comment by jhogendorn** [comment]
no need to be sorry, was more just giving a heads up in case there was an issue :) Thanks for sorting it out!
I've rebuilt my container and it appears resolved.
